### ISSUE TITLE
Make RosettaClientParams.baseUrl required

### ISSUE THREAD

**Issue by rhyslbw** [lunarhq/rosetta-ts-client#8]
I'll be sure to check this library out in more depth, but my cursory review surfaced a minor but important issue regarding adoption. The [fallback to a specific server](https://github.com/lunarhq/rosetta-ts-client/blob/main/src/client.ts#L17) might be a nice convenience for Lunar clients, but it's a boundary violation, and would be confusing for other implementations. I'd suggest just requiring the value passed in explicitly, and would be happy to open a PR if you agree.

Thanks for the work so far!

**Comment by stuartkuentzel** [comment]
Hey @rhyslbw thanks for the feedback! I agree, it's a bit less confusing if we simply make the baseUrl required. If you feel like doing a PR, we'd gladly merge it in.
